In [ ]:
import numpy as np
import torch

test_ids = torch.tensor([1, 2, 3, 4, 5])
mask = torch.tensor([0, 0, 0, 0, 1], dtype=torch.bool)
test_ids[mask]

tensor([5])

In [14]:
input_ids = torch.tensor([[10,11, 0],
                          [20,21,22]])
mask      = torch.tensor([[1, 1, 0],
                          [1, 0, 1]]).bool()

input_ids[mask]
# tensor([10, 11, 20, 22])   # flattened across batch

tensor([10, 11, 20, 22])

In [24]:
input_ids = [
    cur_input_ids[cur_attention_mask]
    for cur_input_ids, cur_attention_mask in zip(input_ids, mask)
]


print(input_ids)
print(tuple(zip(input_ids, mask)))


[tensor([10, 11]), tensor([20, 22])]
((tensor([10, 11]), tensor([ True,  True, False])), (tensor([20, 22]), tensor([ True, False,  True])))


In [26]:
list = [1, 2, 3, 4, 5, 6]
print(list[0:0])

[]
