In [1]:
import numpy as np
import torch

test_ids = torch.tensor([1, 2, 3, 4, 5])
mask = torch.tensor([0, 0, 0, 0, 1], dtype=torch.bool)
test_ids[mask]

tensor([5])

In [2]:
input_ids = torch.tensor([[10,11, 0],
                          [20,21,22]])
mask      = torch.tensor([[1, 1, 0],
                          [1, 0, 1]]).bool()

input_ids[mask]
# tensor([10, 11, 20, 22])   # flattened across batch

tensor([10, 11, 20, 22])

In [3]:
input_ids = [
    cur_input_ids[cur_attention_mask]
    for cur_input_ids, cur_attention_mask in zip(input_ids, mask)
]


print(input_ids)
print(tuple(zip(input_ids, mask)))


[tensor([10, 11]), tensor([20, 22])]
((tensor([10, 11]), tensor([ True,  True, False])), (tensor([20, 22]), tensor([ True, False,  True])))


In [4]:
list = [1, 2, 3, 4, 5, 6]
print(list[0:0])

[]


In [9]:
tool_outputs=[
    {"tool":"chest_xray_classifier","prediction":"cardiomegaly","confidence":0.78,"prior":0.88},
    {"tool":"chest_xray_classifier2","prediction":"cardiomegaly","confidence":0.88,"prior":0.88},
    {"tool":"chest_xray_classifier3","prediction":"cardiomegaly","confidence":0.58,"prior":0.28}

]

scores = []
for out in tool_outputs:
    conf = out["confidence"]
    prior = out["prior"]
    scores.append({"tool" : out["tool"], "score": conf*prior})

scores.sort(key=lambda x: x["score"], reverse=True)
top =scores[0]["score"]
top


0.7744